import { useMemo,useState } from 'react'
import { Link,useParams,useNavigate } from 'react-router-dom'
import { nativeProject,nativeFiles,nativeVersions,saveNativeFile,deleteNativeFile,createNativeVersion,restoreNativeVersion,snapshotDiff,exportNativeProject,deleteNativeProject } from '../utils/nativeProjectStore'

export default function NativeProjectHome(){
 const {id}=useParams(), navigate=useNavigate(), project=nativeProject(id)
 const [files,setFiles]=useState(()=>nativeFiles(id)), [versions,setVersions]=useState(()=>nativeVersions(id))
 const [editing,setEditing]=useState(null), [name,setName]=useState(''), [content,setContent]=useState('')
 const [tab,setTab]=useState('files')
 const [notice,setNotice]=useState('')
 const [openDiff,setOpenDiff]=useState(null)
 const changed=useMemo(()=>editing!==null,[editing])
 if(!project)return <div className="screen-padded"><p className="error-box">That project isn't on this device.</p><Link to="/native/projects">← Your Projects</Link></div>
 function openFile(f){setEditing(f);setName(f.name);setContent(f.content||'')}
 function newFile(){setEditing({id:crypto.randomUUID(),projectId:id});setName('notes.md');setContent('')}
 function save(){if(!name.trim())return; saveNativeFile(id,{...editing,name:name.trim(),content});setFiles(nativeFiles(id));setEditing(null)}
 function remove(f){if(!confirm(`Delete ${f.name}?`))return;deleteNativeFile(id,f.id);setFiles(nativeFiles(id))}
 function checkpoint(){const label=prompt('Name this Save Point','Save Point');if(label===null)return;const v=createNativeVersion(id,label||'Save Point');setVersions(nativeVersions(id));setNotice(v?'':'Nothing changed since your last Save Point, so no new one was made.')}
 function restore(v){if(!confirm(`Restore "${v.label}"? Yourkly first saves your current files as a new Save Point, so nothing gets lost. Then it puts the files back the way they were.`))return;let ok=false;try{ok=restoreNativeVersion(id,v.id)}catch(e){ok=false}setNotice(ok?'':'That Save Point is damaged and cannot be restored.');setFiles(nativeFiles(id));setVersions(nativeVersions(id));setOpenDiff(null)}
 function download(){const data=exportNativeProject(id),blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${project.slug||'yourkly-project'}.yourkly.json`;a.click();URL.revokeObjectURL(url)}
 function removeProject(){if(!confirm(`Delete “${project.name}” from this device?`))return;deleteNativeProject(id);navigate('/native/projects')}
 return <>
  <main className="screen-padded project-screen native-workspace">
   <Link to="/native/projects" className="back-link">← Your Projects</Link>
   <div className="project-head"><div><div className="eyebrow">KEPT WITH YOURKLY</div><h1 className="project-title">{project.name}</h1>{project.description&&<p className="project-desc">{project.description}</p>}</div></div>
   <div className="project-status"><span className="project-status-ok">Kept on this device</span><span className="project-status-sep">|</span><span>{files.length} {files.length===1?'file':'files'}</span><span className="project-status-sep">|</span><span>{versions.length} Save {versions.length===1?'Point':'Points'}</span></div><div className="project-translation-summary"><div><strong>Where am I?</strong><span>This is the home for {project.name}. Your files are the current project. Save Points are earlier versions you can return to.</span></div><div><strong>What should I do next?</strong><span>{files.length?'Open a file to keep working, or make a Save Point before a change you may want to undo.':'Create your first file. Yourkly will keep it inside this project.'}</span></div></div>
   <div className="native-tabs"><button className={tab==='files'?'pl-btn-primary':'pl-btn'} onClick={()=>setTab('files')}>Files</button><button className={tab==='versions'?'pl-btn-primary':'pl-btn'} onClick={()=>setTab('versions')}>Save Points</button><button className={tab==='settings'?'pl-btn-primary':'pl-btn'} onClick={()=>setTab('settings')}>Project</button></div>
   {tab==='files'&&<section className="project-update-card"><div className="section-explainer"><strong>Files = the pieces of your project</strong><span>Open one to read or change it. Creating a Save Point takes a snapshot of all of these files together.</span></div><div className="projects-heading-row"><h2>Files</h2><div><button className="pl-btn" onClick={checkpoint} disabled={!files.length}>Save Point</button> <button className="pl-btn-primary" onClick={newFile}>+ New file</button></div></div>
    {!files.length?<div className="projects-empty"><p>No files yet.</p><button className="pl-btn-primary" onClick={newFile}>Create your first file</button></div>:<div className="native-file-list">{files.map(f=><div className="native-file-row" key={f.id}><button className="text-button" onClick={()=>openFile(f)}><strong>{f.name}</strong></button><button className="text-button" onClick={()=>remove(f)}>Delete</button></div>)}</div>}
   </section>}
   {tab==='versions'&&<section className="project-update-card"><div className="section-explainer"><strong>Save Points = versions you can return to</strong><span>Make one before a big change. If something goes wrong later, Restore puts the project's files back the way they were at that Save Point. Yourkly saves your current files first, so nothing gets lost.</span></div><div className="projects-heading-row"><h2>Save Points</h2><button className="pl-btn-primary" onClick={checkpoint} disabled={!files.length}>Make Save Point</button></div>{notice&&<p className="error-box">{notice}</p>}{!versions.length?<p>No Save Points yet.</p>:versions.map((v,i)=>{const d=openDiff===v.id?snapshotDiff(id,v.id):null;const n=Object.keys(v.files||{}).length;return <div key={v.id}><div className="native-file-row"><span><strong>{v.label}</strong><small>{new Date(v.createdAt).toLocaleString()} · {n} {n===1?'file':'files'}</small></span><span><button className="text-button" onClick={()=>setOpenDiff(openDiff===v.id?null:v.id)}>{openDiff===v.id?'Hide':'What changed'}</button> <button className="pl-btn" onClick={()=>restore(v)}>Restore</button></span></div>{d&&<div className="version-diff">{!d.added.length&&!d.changed.length&&!d.removed.length?<p><small>Nothing changed in this Save Point.</small></p>:<>{d.added.length>0&&<p><small><strong>Added:</strong> {d.added.join(', ')}</small></p>}{d.changed.length>0&&<p><small><strong>Changed:</strong> {d.changed.join(', ')}</small></p>}{d.removed.length>0&&<p><small><strong>Removed:</strong> {d.removed.join(', ')}</small></p>}</>}</div>}</div>})}</section>}
   {tab==='settings'&&<section className="project-update-card"><div className="eyebrow">ABOUT THIS PROJECT</div><h2>Project info</h2><p className="project-info-lead">This page explains what Yourkly is keeping for you and what the project controls mean.</p><div className="project-info-grid"><div><strong>Where your project is</strong><span>Right now, {project.name} is stored in this browser on this device. Yourkly has not uploaded it to GitHub.</span></div><div><strong>What a Save Point does</strong><span>It remembers the contents of your files at a moment in time, so you can return to that version later.</span></div><div><strong>What Export project does</strong><span>It downloads a complete Yourkly copy of the project so you can keep a backup or move it elsewhere.</span></div><div><strong>What Delete project does</strong><span>It removes this Yourkly project from this device. Export first if you may need it later.</span></div></div><div className="newproject-actions"><button className="pl-btn" onClick={download}>Export project</button><button className="pl-btn" onClick={removeProject}>Delete project</button></div></section>}
  </main>
  {editing&&<div className="native-editor-backdrop"><div className="native-editor"><div className="projects-heading-row"><h2>{files.some(f=>f.id===editing.id)?'Edit file':'New file'}</h2><button className="text-button" onClick={()=>setEditing(null)}>Close</button></div><label className="newproject-label">File name</label><input className="newproject-input" value={name} onChange={e=>setName(e.target.value)}/><label className="newproject-label">Contents</label><textarea className="native-editor-text" value={content} onChange={e=>setContent(e.target.value)} autoFocus/><div className="newproject-actions"><button className="pl-btn-primary" onClick={save}>Save file</button><button className="pl-btn" onClick={()=>setEditing(null)}>Cancel</button></div></div></div>}
 </>
}
